services:
  timescaledb:
    image: timescale/timescaledb-ha:pg18
    container_name: timescaledb
    environment:
      - POSTGRES_USER = kbrom
      - POSTGRES_PASSWORD = password
      - POSTGRES_DB=fleet_management_system
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: always
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--notify-keyspace-events", "Ex"]
    restart: always

volumes:
  timescale-data:
  redis_data:
